### ISSUE TITLE
rgba doesn't accept hex colours

### ISSUE THREAD

**Issue by honzapara** [digitalnsw/nsw-design-system-v2#2]
In https://github.com/digitalnsw/nsw-design-system-v2/blob/master/src/components/hero-banner/_hero-banner.scss there is a SASS map which defines light and dark colour. However, the syntax is wrong and this will result in a broken component.

```
$overlays: (
  light: rgba(#ffffff, 0.8),
  dark: rgba(#000000, 0.8)
) !default;
```

should become 

```
$overlays: (
  light: rgba(255, 255, 255, 0.8),
  dark: rgba(0, 0, 0, 0.8)
) !default;
```

**Comment by anna-yeshtukova** [comment]
Hi @honzapara. Thank you for bringing it to our attention. While SCSS does actually accept using rgba(#hex, opacity) it got broken when we used CSS variables in our latest release. Hero banner overlays are now fixed and should be working as expected.
